root: true
env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - google
  - plugin:import/recommended
  - prettier
  - eslint-config-prettier
plugins:
  - prettier
parserOptions:
  ecmaVersion: latest
  parser: babel-eslint
  sourceType: module
  createDefaultProgram: true
rules:
  new-cap: off
  no-invalid-this: off
  no-unused-vars: warn
  prettier/prettier: error
  require-jsdoc: warn
  valid-jsdoc: warn
  no-case-declarations: off
