import eslintPlugin from '@modyqyw/vite-plugin-eslint';
import stylelintPlugin from 'vite-plugin-stylelint';
import { defineConfig } from 'vite';
import path from 'path';
import fs from 'fs';

/** @type {UserConfig} https://vitejs.dev/config/ */
const config = {
  // https://vitejs.dev/config/#server-options
  server: {
    fs: {
      // Allow serving files from one level up to the project root
      allow: ['..'],
    },
  },
  resolve: {
    alias: [
      {
        // this is required for the SCSS modules
        find: /^~(.*)$/,
        replacement: '$1',
      },
    ],
  },
  plugins: [
    // eslint
    // https://github.com/ModyQyW/vite-plugin-eslint
    eslintPlugin(),
    // Stylelint
    // https://github.com/ModyQyW/vite-plugin-stylelint
    stylelintPlugin(),
  ],
  // Build Options
  // https://vitejs.dev/config/#build-options
  build: {
    lib: {
      entry: path.resolve(__dirname, 'src/wml.js'),
      name: 'sf2synth',
      fileName: format => `sf2synth.${format}.js`,
    },
    // Minify option
    // https://vitejs.dev/config/#build-minify
    minify: 'terser',
    terserOptions: {
      ecma: 2020,
      compress: { drop_console: true },
      mangle: true, // Note `mangle.properties` is `false` by default.
      module: true,
      output: { comments: true, beautify: false },
    },
  },
};

// Export vite config
export default defineConfig(async ({ command }) => {
  // Hook production build.
  // Write meta data.

  fs.writeFileSync(
    path.resolve(path.join(__dirname, 'src/meta.js')),
    `// This file is auto-generated by the build system.
const meta = {
  version: '${require('./package.json').version}',
  date: '${new Date().toISOString()}',
};
export default meta;
`
  );

  return config;
});
