const webpack = require('webpack');
const fs = require('fs');
const path = require('path');
const TerserPlugin = require('terser-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const CssMinimizerPlugin = require('css-minimizer-webpack-plugin');
const CopyPlugin = require('copy-webpack-plugin');

const pjson = require('./package.json');
const build = new Date().toISOString();

/**
 * Webpack Config
 * @param {any} env
 * @param {any} argv
 * @return {webpack.Configuration}
 */
module.exports = (env, argv) => {
  const isProduction = argv.mode === 'production';
  const banner = `${pjson.name} v${pjson.version} | ${pjson.author.name} / ${pjson.contributors[0].name} | license: ${pjson.license} | build: ${build}`;

  const plugins = [
    new webpack.BannerPlugin({
      banner: banner,
    }),
    new MiniCssExtractPlugin({
      // ファイル名を設定します
      filename: !isProduction ? '[name].css' : '[name].min.css',
    }),
    new CopyPlugin({
      patterns: [
        { from: 'bin/sf2.synth.js', to: '../docs' },
        { from: 'bin/sf2.synth.js.map', to: '../docs' },
        { from: 'bin/wml.css', to: '../docs' },
      ],
    }),
  ];

  if (isProduction) {
    fs.writeFileSync(
      path.resolve(path.join(__dirname, 'src/meta.js')),
      `// This file is auto-generated by the build system.
const Meta = {
  version: '${pjson.version}',
  date: '${build}',
};
export default Meta;`
    );
  }

  return {
    mode: env,
    target: ['web'],
    entry: {
      'sf2.synth': './src/wml.js',
      'sf2.parser': './src/sf2.js',
      wml: './src/wml.scss',
    },
    output: {
      path: path.resolve(__dirname, 'bin'),
      filename: !isProduction ? '[name].js' : '[name].min.js',
      library: 'SoundFont',
      libraryTarget: 'umd',
      umdNamedDefine: true,
      globalObject: `(typeof self !== 'undefined' ? self : this)`,
    },
    optimization: {
      minimize: isProduction,
      minimizer: [
        new TerserPlugin({
          test: /\.js(\?.*)?$/i,
          extractComments: true,
          terserOptions: {
            ecma: 2020,
            compress: { drop_console: true },
            output: {
              comments: false,
              beautify: false,
            },
          },
        }),
        new CssMinimizerPlugin(),
      ],
      splitChunks: {
        minSize: 0,
      },
      concatenateModules: false,
    },
    module: {
      rules: [
        // 拡張子 .js の場合
        {
          test: /\.jsx?$/,
          exclude: /node_modules/,
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env'],
            plugins: ['@babel/plugin-transform-runtime'],
          },
        },
        // Sassファイルの読み込みとコンパイル
        {
          test: /\.s[ac]ss$/i,
          use: [MiniCssExtractPlugin.loader, 'css-loader', 'sass-loader'],
        },
      ],
    },
    resolve: {
      modules: [`${__dirname}/src`, 'node_modules'],
      extensions: ['.js', '.scss'],
    },
    plugins: plugins,
    devtool: !isProduction ? 'source-map' : false,
    devServer: {
      static: {
        directory: path.join(__dirname, 'docs'),
      },
      client: {
        overlay: true,
      },
      port: 8080,
    },
  };
};
