// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../closure-primitives/base.js', ['goog'], [], false);
goog.addDependency('../define/typedarray/hybrid.js', ['USE_TYPEDARRAY'], [], false);
goog.addDependency('../define/typedarray/use.js', ['USE_TYPEDARRAY'], [], false);
goog.addDependency('../src/default_ir.js', ['SoundFont.DefaultIR'], [], false);
goog.addDependency('../src/riff.js', ['Riff.Parser'], ['Typedef'], false);
goog.addDependency('../src/sf2.js', ['SoundFont.Parser'], ['Riff.Parser', 'Typedef'], false);
goog.addDependency('../src/sound_font_synth.js', ['SoundFont.Synthesizer'], ['SoundFont.DefaultIR', 'SoundFont.Parser', 'SoundFont.SynthesizerNote'], false);
goog.addDependency('../src/sound_font_synth_note.js', ['SoundFont.SynthesizerNote'], [], false);
goog.addDependency('../src/typedef.js', ['Typedef'], [], false);
goog.addDependency('../src/wml.js', ['SoundFont.WebMidiLink'], ['SoundFont.Synthesizer'], false);
